{
 "title": "Сервисы RG",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5s",
 "panels": [
  { "title": "file-uploader", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Общие сведения",
   "type": "text",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 1 },
   "content": "\n# file-uploader\n\nМикросервис загрузки файлов, и обрезки загруженных изображений\n\n- **url:**  https://file-uploader.rg.ru/\n\n- **metrics:** https://file-uploader.rg.ru/metrics\n\n- **git:** https://git.rgwork.ru/masterback/rgru-file-uploader\n\n\n\n\n"
  },
  {
   "title": "Память кучи в байтах.  # Number of heap bytes obtained from system",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 6 },
   "targets": [
    {
     "expr": "go_memstats_heap_sys_bytes{job=\"file-uploader\"}"
    }
   ]
  },
  {
   "title": "HTTP запросы в минуту",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 6 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(http_requests_total{job=\"file-uploader\"}[1m])"
    }
   ]
  },
  {
   "title": "HTTP запросы всего",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 6 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "http_requests_total{job=\"file-uploader\"}"
    }
   ]
  },
  { "title": "auth-proxy", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 } },
  {
   "title": "Panel Title",
   "type": "text",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 14 },
   "content": "\n# auth-proxy\n\nПользовательская авторизация\n\n- **admin:**&nbsp;&nbsp;&nbsp;  https://auth-proxy.rg.ru/admin\n\n- **metrics:** https://auth-proxy.rg.ru/metrics\n\n- **git:** https://git.rgwork.ru/masterback/auth-proxy\n\n\n"
  },
  {
   "title": "Память байт. # Number of bytes obtained from system",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 20 },
   "targets": [
    {
     "expr": "go_memstats_sys_bytes{job=\"auth-proxy\"}"
    }
   ]
  },
  {
   "title": "HTTP запросы в минуту",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 20 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(http_requests_total{job=\"auth-proxy\"}[1m])"
    }
   ]
  },
  {
   "title": "HTTP запросы (всего)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 20 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "http_requests_total{job=\"auth-proxy\"}"
    }
   ]
  }
 ]
}