{
 "title": "Сервисы RG",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "job",
    "label": "Приложение",
    "query": "auth-proxy, file-uploader, photoreports-admin-prod"
   }
  ]
 },
 "panels": [
  { "title": "Go приложение", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  { "type": "text", "gridPos": { "h": 2, "w": 24, "x": 0, "y": 1 }, "content": "\n# [[job]]\n\n\n\n" },
  {
   "type": "gauge",
   "gridPos": { "h": 4, "w": 20, "x": 0, "y": 3 },
   "targets": [
    {
     "expr": "go_goroutines{job=~\"${job:regex}\"}",
     "legendFormat": "goroutines {{job}}"
    },
    {
     "expr": "go_threads{job=~\"${job:regex}\"}",
     "legendFormat": "threads {{job}}"
    }
   ]
  },
  {
   "title": "Память мегабайт. # Number of Megabytes obtained from system",
   "type": "bargauge",
   "gridPos": { "h": 6, "w": 5, "x": 0, "y": 7 },
   "targets": [
    {
     "expr": "go_memstats_sys_bytes{job=~\"${job:regex}\"} /1024 /1024",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "HTTP запросы в минуту",
   "type": "graph",
   "gridPos": { "h": 6, "w": 5, "x": 5, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(http_requests_total{job=~\"${job:regex}\"}[1m])*60",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "GraphQL ошибки в минуту",
   "type": "graph",
   "gridPos": { "h": 6, "w": 5, "x": 10, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(graphql_errors_total{job=~\"${job:regex}\"}[1m])*60",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Время процессора потраченное за секунду",
   "type": "graph",
   "gridPos": { "h": 6, "w": 5, "x": 15, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(process_cpu_seconds_total{job=~\"${job:regex}\"}[1m])",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Аллоцированных  и используемых мегабайт",
   "type": "graph",
   "gridPos": { "h": 6, "w": 5, "x": 15, "y": 13 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "go_memstats_alloc_bytes{job=~\"${job:regex}\"}/1024/1024",
     "legendFormat": "{{job}}"
    }
   ]
  },
  { "title": "file-uploader", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 } },
  {
   "type": "text",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 20 },
   "content": "\n# file-uploader\n### [[job]]\n\n##### Микросервис загрузки файлов, и обрезки загруженных изображений\n\n- **url:**  https://file-uploader.rg.ru/\n\n- **metrics:** https://file-uploader.rg.ru/metrics\n\n- **git:** https://git.rgwork.ru/masterback/rgru-file-uploader\n\n\n\n\n"
  },
  {
   "title": "Number of heap Megabytes obtained from system",
   "type": "bargauge",
   "gridPos": { "h": 6, "w": 5, "x": 0, "y": 25 },
   "targets": [
    {
     "expr": "go_memstats_heap_sys_bytes{job=\"file-uploader\"} / 1024 / 1024"
    }
   ]
  },
  {
   "title": "HTTP запросы в минуту",
   "type": "graph",
   "gridPos": { "h": 6, "w": 5, "x": 5, "y": 25 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(http_requests_total{job=\"file-uploader\"}[1m])*60"
    }
   ]
  },
  {
   "title": "GraphQL ошибки в минуту",
   "type": "graph",
   "gridPos": { "h": 6, "w": 5, "x": 10, "y": 25 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(graphql_errors_total{job=\"file-uploader\"}[1m])*60"
    }
   ]
  },
  { "title": "auth-proxy", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 31 } },
  {
   "type": "text",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 32 },
   "content": "\n# auth-proxy\n\n- **admin:**&nbsp;&nbsp;&nbsp;  https://auth-proxy.rg.ru/admin\n\n- **metrics:** https://auth-proxy.rg.ru/metrics\n\n- **git:** https://git.rgwork.ru/masterback/auth-proxy\n\n\n"
  },
  {
   "title": "Память мегабайт. # Number of Megabytes obtained from system",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 5, "x": 0, "y": 36 },
   "targets": [
    {
     "expr": "go_memstats_sys_bytes{job=\"auth-proxy\"} /1024 /1024"
    }
   ]
  },
  {
   "title": "HTTP запросы в минуту",
   "type": "graph",
   "gridPos": { "h": 6, "w": 5, "x": 5, "y": 36 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(http_requests_total{job=\"auth-proxy\"}[1m])*60",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "GraphQL ошибки в минуту",
   "type": "graph",
   "gridPos": { "h": 6, "w": 5, "x": 10, "y": 36 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(graphql_errors_total{job=\"auth-proxy\"}[1m])*60"
    }
   ]
  }
 ]
}